/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;
import supermarket.Payment;

/**
 *
 * @author lektor
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public print() {
        initComponents();
    }
    
    
    String lSubtotal;
    String lPayed;
    String lBalance;
    
    //saljemo u konstruktor elemente koje želimo printati
     public print(String subtotal, String payed, String balance, TableModel tableModel) throws PrinterException {
        initComponents();
        
        this.lSubtotal=subtotal;
        this.lPayed=payed;
        this.lBalance=balance;
        
        
        txtPrint.setText(txtPrint.getText()+"************************************************************\n");
         txtPrint.setText(txtPrint.getText()+"*****************SellingDigital*******************************\n");
         txtPrint.setText(txtPrint.getText()+"\n");
         txtPrint.setText(txtPrint.getText()+"PRODUCT"+"\t"+"PRICE"+"\t"+"TOTAL"+"\n");
         
         for(int i =0; i<tableModel.getRowCount();i++)
         {
             String product = (String) tableModel.getValueAt(i,1);
             String price = (String) tableModel.getValueAt(i,2);
             Double total = (Double) tableModel.getValueAt(i,4);
             
             txtPrint.setText(txtPrint.getText()+product +"\t"+price+"\t"+total+"\n");
         }
            txtPrint.setText(txtPrint.getText()+"\n");
            txtPrint.setText(txtPrint.getText()+"\n");
            txtPrint.setText(txtPrint.getText()+"\n");
            
            
            txtPrint.setText(txtPrint.getText()+"            "+"SUBTOTAL : "+ subtotal+    "\n");
          txtPrint.setText(txtPrint.getText()+"            "+"PAYED : "+ payed+    "\n");
          txtPrint.setText(txtPrint.getText()+"            "+"REST : "+ balance+    "\n");
          
          txtPrint.setText(txtPrint.getText()+"************************************************************\n");
         txtPrint.setText(txtPrint.getText()+"THANK YOU & SEE YOU SOON AGAIN \n");
         
         
         txtPrint.print();
    }
    
    public Payment window(){
        Payment ps = new Payment();
        this.hide();
        ps.setVisible(true);
        return ps;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrint = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPrint.setColumns(20);
        txtPrint.setRows(5);
        jScrollPane1.setViewportView(txtPrint);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButton1)
                .addContainerGap(150, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
window();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPrint;
    // End of variables declaration//GEN-END:variables
}
